# The list topics_list is AI generated
# Except this nothing in this assignment is AI Generated

topics_list = [
    "Astronomy",
    "Ancient civilizations",
    "Quantum physics",
    "World War II stories",
    "Philosophy",
    "Machine learning",
    "Artificial intelligence",
    "Space exploration",
    "Cryptocurrency",
    "Blockchain technology",
    "Sustainable energy",
    "Climate change",
    "Oceanography",
    "Wildlife conservation",
    "National parks",
    "Endangered species",
    "Programming tips",
    "Python programming",
    "Data science",
    "Web development",
    "Mobile app development",
    "Video game design",
    "Augmented reality",
    "Virtual reality",
    "History of technology",
    "Famous inventors",
    "Scientific breakthroughs",
    "Medical discoveries",
    "Psychology",
    "Neuroscience",
    "Dream interpretation",
    "Ancient mythology",
    "Folktales",
    "Science fiction",
    "Fantasy worlds",
    "Book recommendations",
    "Movie reviews",
    "TV series recommendations",
    "Music history",
    "Famous musicians",
    "Art history",
    "Modern art",
    "Famous paintings",
    "Photography tips",
    "Creative writing prompts",
    "Daily affirmations",
    "Motivational quotes",
    "Success stories",
    "Entrepreneurship",
    "Startup ideas",
    "Marketing strategies",
    "Finance tips",
    "Investing basics",
    "Real estate tips",
    "Personal development",
    "Productivity hacks",
    "Time management",
    "Mindfulness",
    "Meditation techniques",
    "Yoga tips",
    "Fitness routines",
    "Healthy eating",
    "Cooking recipes",
    "Food cultures",
    "Travel destinations",
    "Backpacking tips",
    "Camping guides",
    "Cultural festivals",
    "Languages to learn",
    "Word origins",
    "Poetry snippets",
    "Famous speeches",
    "Quotes from authors",
    "Hobbies to try",
    "DIY crafts",
    "Gardening tips",
    "Interior design",
    "Minimalist living",
    "Digital decluttering",
    "Home automation",
    "Gadget reviews",
    "Tech trends",
    "Coding challenges",
    "Math puzzles",
    "Chess strategies",
    "Board game reviews",
    "Card games",
    "Magic tricks",
    "Esports news",
    "Sports highlights",
    "Famous athletes",
    "Olympic history",
    "Martial arts",
    "Astrology",
    "Zodiac traits",
    "Tarot card readings",
    "Urban legends",
    "Ghost stories",
    "True crime",
    "Detective fiction",
    "Survival skills",
    "Life hacks"
]
